# Generated by Django 3.1.4 on 2021-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
